// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Phase } from "./Phase";
import type { Player } from "./Player";
import type { SkullState } from "./SkullState";

export interface ClientGameState { phase: Phase, players: Array<Player>, active_player: number, own_skull: SkullState, }