// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClientMessage = "Start" | { SelectCard: boolean } | { Bid: number } | "Skip" | { SelectPlayer: number } | "Sync";