// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlayerInfo } from "./PlayerInfo";

export interface LobbyState { players: Array<PlayerInfo>, own_id: string, host_id: string, }