// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Phase = "Waiting" | "Preparation" | "AddingCards" | "Challenge" | "Discarding" | "DiscardingOwn" | "GameOver" | "PlayerSelection" | "Revealing" | "RevealingOwn";