// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Player { id: number, placed_cards: number, hand: number, wins: number, bid: number | null, pass: boolean | null, revealed: number | null, }