// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientGameState } from "./ClientGameState";
import type { LobbyState } from "./LobbyState";

export type ServerEvent = { SessionId: string } | { PlayerJoined: [string, string] } | { PlayerLeft: [string, string] } | { Start: number } | { PlayerPlacedCard: number } | { ActivePlayerBid: number } | "ActivePlayerPassed" | { PlayerCardRevealed: [number, boolean] } | "ActivePlayerCardDiscarded" | { OwnCardDiscarded: boolean } | { NextPlayer: number } | { State: [ClientGameState, LobbyState] };